Add Python checks to GitHub Actions workflow

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -30,6 +30,67 @@ jobs:
       - name: Lint
         run: npm run lint
 
+  lint-python:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+      - uses: actions/setup-python@v6
+        with:
+          python-version: 3.11
+
+      - name: Install Ruff
+        run: |
+          python -m pip install --upgrade pip
+          pip install ruff
+
+      - name: Lint
+        run: ruff check . --output-format github
+
+  check-python-requirements:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+      - uses: actions/setup-python@v6
+        with:
+          python-version: 3.11
+
+      - name: Check unused requirements
+        run: |
+          # Spin up a clean venv so pip-extra-reqs can map package metadata
+          python -m venv .venv
+          source .venv/bin/activate
+
+          # Install pip dependencies and pip-check-reqs
+          # pip dependecies must be installed for pip-extra-reqs to work
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt pip-check-reqs
+
+          # Run pip-extra-reqs and save to a temp file
+          # so a failure code doesn't stop the workflow early
+          #
+          # If this command is incorrectly classifying a requirement as "extra,"
+          # double check that it's required and add "-r package_name"
+          # (eg "pip-extra-reqs . -r some_package -r another_package > extra_reqs.txt")
+          pip-extra-reqs . > extra_reqs.txt 2>&1 || true
+
+          # Print the command output to the console so devs can inspect it
+          cat extra_reqs.txt
+
+          # Filter for the packages and loop through them
+          grep "in requirements.txt" extra_reqs.txt | awk '{print $1}' | while read -r pkg; do
+            
+            # Find the line number of that package in requirements.txt
+            line_num=$(grep -n -m 1 "^$pkg" requirements.txt | cut -d: -f1)
+            
+            # Print the GitHub inline warning (default to line 1 if not found)
+            echo "::error file=requirements.txt,line=${line_num:-1},title=Unused Requirement::$pkg is required but doesn't seem to be used."
+          done
+
+          # Force the workflow job to fail if extra requirements exist
+          if grep -q "in requirements.txt" extra_reqs.txt; then
+            exit 1
+          fi
+
   check-js-formatting:
     runs-on: ubuntu-latest
     steps:
@@ -63,7 +124,7 @@ jobs:
         with:
           python-version: 3.11
 
-      - name: Install Dependencies
+      - name: Install pip requirements
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
@@ -97,7 +158,7 @@ jobs:
         with:
           python-version: 3.11
 
-      - name: Install Dependencies
+      - name: Install pip requirements
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
@@ -119,13 +180,13 @@ jobs:
         || (github.event_name == 'workflow_dispatch' && inputs.perform_deploy)
     # Wait for tests to pass
     needs:
-      [
-        lint-js,
-        check-js-formatting,
-        check-js-types,
-        check-pending-migrations,
-        test-python,
-      ]
+      - lint-js
+      - lint-python
+      - check-python-requirements
+      - check-js-formatting
+      - check-js-types
+      - check-pending-migrations
+      - test-python
     runs-on: ubuntu-latest
     environment:
       name: ${{ inputs.environment || 'Staging' }}
@@ -146,7 +207,7 @@ jobs:
         with:
           python-version: 3.11
 
-      - name: Install Dependencies
+      - name: Install pip requirements
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
